name: mangaturn
description: A manga reader application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  shared_preferences: ^2.0.6
  random_color: ^1.0.6-nullsafety
  date_format: ^2.0.4
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  clipboard: ^0.1.3
  share:
#    git:
#      url: git://github.com/himanshusharma89/plugins.git
#      path: packages/share
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  firebase_messaging: ^10.0.5
  sqflite: ^2.0.0+3
  path: ^1.8.0
#  network_image_to_byte: ^0.0.1
  permission_handler: ^8.1.4+2
  fluttertoast: ^8.0.8
  flutter_local_notifications: ^5.0.0+4
  dio: ^4.0.0
#  wallpaper_manager: ^1.0.10
  flutter_cache_manager: ^3.1.2
  device_apps:
  retrofit: ^2.0.1
  logger: ^1.0.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  flutter_slidable: ^0.6.0
  get_it: ^7.1.3
  html: ^0.15.0
  font_awesome_flutter: ^9.1.0
  file_picker:
  dio_flutter_transformer:
    git:
      url: https://github.com/GiorgiBeriashvili/dio_flutter_transformer
      ref: feature/null-safety
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  image_downloader: ^0.31.0
  salomon_bottom_bar: ^3.1.0
  shimmer: ^2.0.0
  multi_image_picker: ^4.8.01
  flutter_linkify: ^5.0.2
  flutter_staggered_animations: ^1.0.0
  firebase_dynamic_links: ^2.0.8
  hive:
  google_mobile_ads: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.1
  build_runner: ^2.1.1
  json_serializable: ^4.1.4
  json_annotation: ^4.0.1
  flutter_launcher_icons: "^0.9.1"
  infinite_scroll_pagination: ^3.1.0
  hive_generator:
  hive_flutter:
  timeago:
  readmore: ^2.1.0
  getwidget: ^2.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/test_img/
    - assets/icon/icon.png

  fonts:
    - family: mm
      fonts:
        - asset: fonts/mm.ttf
    - family: baloo2
      fonts:
        - asset: fonts/Baloo2-Regular.ttf
        - asset: fonts/Baloo2-Bold.ttf
          weight: 500
        - asset: fonts/Baloo2-ExtraBold.ttf
          weight: 600
        - asset: fonts/Baloo2-Medium.ttf
          weight: 300
        - asset: fonts/Baloo2-SemiBold.ttf
          weight: 400
    - family: wp
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Medium.ttf

